[package]
name = "Pinout"
version = "1.0.1"
edition = "2021"
authors = [ "IHateYourCode <https://github.com/IHateYourCode>" ]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[dependencies]
web-view = { version = "0.7" }

[[bin]]
name = "Pinout"
path = "src/main.rs"
